[project]
name = "maximumplay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "attachments>=0.15.0",
    "dspy>=2.6.27",
    "ipykernel>=6.29.5",
]
